import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Banner } from "@/components/banner";
import { Header } from "@/components/header";
import { Footer } from "@/components/sections/footer";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased font-montserrat`}>
        <Banner />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
